config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticated :user do
    root "categories#index", as: :authenticated_root
  end
  root "welcome#index"
  resources :categories, only: [:index, :new, :show, :create]
  resources :expenses, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :expenses

  validates :name, presence: true, length: { minimum: 3, maximum: 20 }
  validates :icon, presence: true
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :category

  validates :name, presence: true, length: { minimum: 3, maximum: 20 }
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories
  has_many :expenses

  validates :name, presence: true, length: { minimum: 3, maximum: 50 }
  validate :fullname

  def fullname
    return unless name.split.size != 2

    errors.add(:name, 'must contain two names separated by a space')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
  end

  def after_sign_in_path_for(_resource)
    categories_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = Category.all
    @expenses = Expense.all
    @total = @expenses.sum(:amount)
    @category_totals = calculate_categories_totals
  end

  def show
    @category = Category.find_by(id: params[:id])
    @expenses = Expense.where(category_id: params[:id]).order(created_at: :desc)
    @total_for_category = @expenses.sum(:amount)
  end

  def new
    @category = Category.new
    @icons = ['&#x1F374;', '&#x2708;', '&#x1F393;', '&#x1F489;', '&#x1F697;', '&#x1F4A1;', '&#x1F3E0;', '&#x1F3A7;',
              '&#x1F6CD;', '&#x1F381;']
  end

  def create
    @icons = ['&#x1F374;', '&#x2708;', '&#x1F393;', '&#x1F489;', '&#x1F697;', '&#x1F4A1;', '&#x1F3E0;', '&#x1F3A7;',
              '&#x1F6CD;', '&#x1F381;']
    @category = Category.new(category_params)
    @category.user = current_user

    if @category.save
      redirect_to categories_path
    else
      pp @category.errors
      render 'new'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon, :category_id, :user_id)
  end

  def calculate_categories_totals
    category_totals = {}

    @categories.each do |category|
      category_expenses = @expenses.where(category_id: category.id)
      total = category_expenses.sum(:amount)
      category_totals[category.name] = total
    end

    category_totals
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!

  def new
    @expense = Expense.new
    @categories = Category.all
  end

  def create
    @user = current_user
    @categories = Category.all
    @expense = Expense.new(expense_params)
    @expense.author = @user
    if @expense.save
      redirect_to category_path(@expense.category_id)
    else
      pp @expense.errors
      render 'new'
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount, :category_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<%# path: app/views/categories/index.html.erb %>
<div class="categories-index">
  <div class="header">
    <span><a href="<%= root_path %>" class="back-arrow">←</a></span>
    <span>CATEGORIES</span>
    <span><a href="<%= categories_path %>" class="back-arrow">&#128269;</a></span>
  </div>
  <div class="gift-credit">
    <span>Total for all categories:</span>
    <span>$ <%= @total %></span>
  </div>
  <hr>
  <ul>
    <% @categories.each do |category| %>
      <%= link_to category do %>
        <li>
          <div class="left">
            <%= content_tag(:span, raw(category.icon), class: "category-icon") %>
            <span><%= category.name %></span>
          </div>
          <div class="right">
            <span>total: </span>
            <span> $ <%= @category_totals[category.name] %></span>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
  <div class="add-category">
    <%= link_to new_category_path, class: "add-category-border" do %>
      <div class="add-category-link">ADD CATEGORY</div>
    <% end %>
  </div>
</div>
</div>

app/views/categories/new.html.erb
<%# path: app/views/categories/new.html.erb %>
<div class="categories-index">
  <div class="header">
    <span><a href="<%= root_path %>" class="back-arrow">←</a></span>
    <span>ADD CATEGORY</span>
    <span><a href="<%= new_category_path %>" class="back-arrow">&#128269;</a></span>
  </div>

  <% if @category.errors.any? %>
  asñdkflj
  <% end %>

  <%= form_for(@category) do |f| %>
    <div class="field">
      <%= f.text_field :name, autocomplete: "off", placeholder: "Name", required: true %>
    </div>
    <hr>
    <div class="field-icon">
      <%= f.select :icon, options_for_select(@icons.map { |icon| [icon.html_safe, icon] }, @icons.first), {}, autocomplete: "off" %>
    </div>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <div class="add-category">
      <div class="add-category-border">
        <%= f.submit "CREATE", class:"add-category-link" %>
      </div>
    </div>
  <% end %>
</div>

app/views/categories/show.html.erb
<%# path: app/views/categories/show.html.erb %>

<div class="categories-index">
  <div class="header">
    <span><a href="<%= root_path %>" class="back-arrow">←</a></span>
    <span>
      <%= @category.name %>
    </span>
    <span><a href="<%= category_path %>" class="back-arrow">&#128269;</a></span>
  </div>
  <div class="gift-credit">
    <span>Total for <%= @category.name %></span>
    <span>$ <%= @total_for_category %></span>
  </div>
  <hr>
  <ul>
    <% @expenses.each do |expense| %>
      <li class="categories-show-li">
        <div class="left">
          <%= expense.name %>
        </div>
        <div class="right">
          $ <%= expense.amount %>
        </div>
      </li>
    <% end %>
  </ul>
  <%= link_to new_expense_path, class: "add-category" do %>
    <div class="add-category-border">
      <div class="add-category-link">ADD EXPENSE</div>
    </div>
  <% end %>
</div>

app/views/expenses/new.html.erb
<%# path = app/views/expenses/new.html.erb %>
<div class="categories-index">
  <div class="header">
    <span><a href="<%= categories_path %>" class="back-arrow">←</a></span>
    <span>ADD EXPENSE</span>
    <span><a href="<%= categories_path %>" class="back-arrow">&#128269;</a></span>
  </div>
  <%= form_for(@expense) do |f| %>
    <hr>
    <div class="field">
      <%= f.text_field :name, placeholder: "Name", required: true %>
    </div>
    <hr>
    <div class="field">
      <%= f.number_field :amount, placeholder: "Amount", required: true %>
    </div>
    <hr>
    <div class="field-icon field-category">
      <%= f.collection_select :category_id, @categories, :id, :name, prompt: "Select a Category", required: true %>
    </div>
    
    <div class="add-category">
      <div class="add-category-border">
        <%= f.submit "SAVE", class:"add-category-link" %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;700&display=swap" rel="stylesheet">

  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<%# path: app/views/welcome/index.html.erb %>

<div class="login-signup">
  <div class="up">
    <h1>BudgeTracker</h1>
  </div>
  <div class="down">
    <%= link_to new_user_session_path, class: "login-btn" do %>
      <div class="login-btn-link">LOG IN</div>
    <% end %>
    <%= link_to new_user_registration_path, class: "signup-btn" do %>
      <div class="signup-btn-link">SIGN UP</div>
    <% end %>
  </div>
</div>